#!/bin/bash

mkdir -p "$PKG_PATH/usr/"

cp -rp /pkg/src/cosmos/cosmos-*-one-jar.jar "$PKG_PATH/usr/cosmos.jar"
sudo chmod -R o+r "$PKG_PATH/usr"

cosmos_service="$PKG_PATH/dcos.target.wants_master/dcos-cosmos.service"
mkdir -p $(dirname "$cosmos_service")

cat <<EOF > "$cosmos_service"
[Unit]
Description=Cosmos
After=dcos-mesos-master.service
[Service]
Restart=always
StartLimitInterval=0
RestartSec=15
EnvironmentFile=/opt/mesosphere/etc/num_masters.env
EnvironmentFile=/opt/mesosphere/environment
ExecStartPre=/opt/mesosphere/bin/exhibitor_wait.py \$ZOOKEEPER_CLUSTER_SIZE
## CoreOS
ExecStartPre=-/usr/bin/mkdir -p /var/lib/cosmos
## Ubuntu
ExecStartPre=-/bin/mkdir -p /var/lib/cosmos
ExecStart=/opt/mesosphere/bin/java -Xmx2G -jar "$PKG_PATH/usr/cosmos.jar"
EOF
