#%RAML 1.0 Resource
post:
  description: |
    Lists all of the running DC/OS services started from a DC/OS package.
  headers:
    Accept:
      enum: [application/vnd.dcos.package.list-response+json;charset=utf-8;version=v1]
  body:
    application/vnd.dcos.package.list-request+json;charset=utf-8;version=v1:
      type: !include ../schemas/cosmos/rpc/v1/model/ListRequest-schema.json
      example: {}
  responses:
    200:
      body:
        application/vnd.dcos.package.list-response+json;charset=utf-8;version=v1:
          type: !include ../schemas/cosmos/rpc/v1/model/ListResponse-schema.json
          example:
            packages:
              - appId: /cassandra
                packageInformation:
                  packageDefinition:
                    packagingVersion: "3.0"
                    name: cassandra
                    version: 1.0.24-3.0.10
                    maintainer: support@mesosphere.io
                    description: Apache Cassandra
                    tags:
                      - database
