#%RAML 1.0 Resource
get:
  description: |
    This endpoint is used to access the resources that are rewritten by cosmos. The query parameter named `url` specifies the actual url of the resource when it was added to universe repo.
  queryParameters:
    url:
      description: The url of the resource that was used when it was added to the universe.
      type:        string
      required:    true
      example:     http://somedomain.com/resource.txt
  responses:
    200:
      headers:
        Content-Disposition:
          description: The first parameter is `attachment` (indicating it should be downloaded; most browsers presenting a 'Save as' dialog, prefilled with the value of the filename parameters if present). The second part is the name of the file.
          example: attachment; filename="resource.txt"
      body:
        application/octet-stream:
          type: file
          fileTypes: ['*/*']
          minLength: 0
          maxLength: 104857600
