#%RAML 1.0 Resource
post:
  description: |
    Adds a package repository (for example Universe) for use by DC/OS. To add a package
    repository to the beginning of the list set the index to zero (0). To add a package
    repository to the end of the list do not specify an index.
  headers:
    Accept:
      enum: [application/vnd.dcos.package.repository.add-response+json;charset=utf-8;version=v1]
  body:
    application/vnd.dcos.package.repository.add-request+json;charset=utf-8;version=v1:
      type: !include ../schemas/cosmos/rpc/v1/model/PackageRepositoryAddRequest-schema.json
      example:
        name: Local Universe
        uri: http://universe.marathon.mesos:8080/repo
  responses:
    200:
      body:
        application/vnd.dcos.package.repository.add-response+json;charset=utf-8;version=v1:
          type: !include ../schemas/cosmos/rpc/v1/model/PackageRepositoryAddResponse-schema.json
          example:
            repositories:
              - name: Universe
                uri: https://universe.mesosphere.com/repo
              - name: Local Universe
                uri: http://universe.marathon.mesos:8080/repo
