#%RAML 1.0 Resource
post:
  description: |
    Generates the Marathon application definition for the package name, version, and optional
    configuration JSON object.
  headers:
    Accept:
      enum: [application/vnd.dcos.package.render-response+json;charset=utf-8;version=v1]
  body:
    application/vnd.dcos.package.render-request+json;charset=utf-8;version=v1:
      type: !include ../schemas/cosmos/rpc/v1/model/RenderRequest-schema.json
      example:
        packageName: cassandra
        packageVersion: 1.0.24-3.0.10
  responses:
    200:
      body:
        application/vnd.dcos.package.render-response+json;charset=utf-8;version=v1:
          type: !include ../schemas/cosmos/rpc/v1/model/RenderResponse-schema.json
          example:
            marathonJson:
              id: /cassandra
              mem: 500.0
              cpus: 1.0