#%RAML 1.0 Resource
post:
  description: |
    Lists all matching packages in the repository given a partial pattern.
    The character \'\*\' can be used to match any number of characters.
  headers:
    Accept:
      enum: [application/vnd.dcos.package.search-response+json;charset=utf-8;version=v1]
  body:
    application/vnd.dcos.package.search-request+json;charset=utf-8;version=v1:
      type: !include ../schemas/cosmos/rpc/v1/model/SearchRequest-schema.json
      example:
        query: database
  responses:
    200:
      body:
        application/vnd.dcos.package.search-response+json;charset=utf-8;version=v1:
          type: !include ../schemas/cosmos/rpc/v1/model/SearchResponse-schema.json
          example:
            packages:
              - name: cassandra
                currentVersion: 1.0.24-3.0.10
                versions:
                  1.0.24-3.0.10: 24
                  1.0.23-3.0.10: 23
                description: Apache Cassandra
                framework: true
                tags:
                  - database
