#%RAML 1.0 Resource
post:
  description: Stops a running service that was launched from a DC/OS package.
  headers:
    Accept:
      enum: [application/vnd.dcos.package.uninstall-response+json;charset=utf-8;version=v1]
  body:
    application/vnd.dcos.package.uninstall-request+json;charset=utf-8;version=v1:
      type: !include ../schemas/cosmos/rpc/v1/model/UninstallRequest-schema.json
      example:
        packageName: cassandra
        appId: /cassandra
  responses:
    200:
      body:
        application/vnd.dcos.package.uninstall-response+json;charset=utf-8;version=v1:
          type: !include ../schemas/cosmos/rpc/v1/model/UninstallResponse-schema.json
          example:
            results:
              - packageName: cassandra
                appId: /cassandra