#%RAML 1.0 Resource
post:
  description: Runs a service from a Universe package.
  headers:
    Accept:
      enum: [application/vnd.dcos.package.install-response+json;charset=utf-8;version=v2]
  body:
    application/vnd.dcos.package.install-request+json;charset=utf-8;version=v1:
      type: !include ../schemas/cosmos/rpc/v1/model/InstallRequest-schema.json
      example:
        packageName: cassandra
        packageVersion: 1.0.24-3.0.10
  responses:
    200:
      body:
        application/vnd.dcos.package.install-response+json;charset=utf-8;version=v2:
          type: !include ../schemas/cosmos/rpc/v2/model/InstallResponse-schema.json
          example:
            packageName: cassandra
            packageVersion: 1.0.24-3.0.10
            appId: /cassandra
