#%RAML 1.0 Resource
post:
  description: |
    Show information about the package, including the required resources and configuration to
    start the service, and command line extensions that are included with the package.
  headers:
    Accept:
      enum: [application/vnd.dcos.package.describe-response+json;charset=utf-8;version=v2]
  body:
    application/vnd.dcos.package.describe-request+json;charset=utf-8;version=v1:
      type: !include ../schemas//cosmos/rpc/v1/model/DescribeRequest-schema.json
      example:
        packageName: cassandra
        packageVersion: 1.0.24-3.0.10
  responses:
    200:
      body:
        application/vnd.dcos.package.describe-response+json;charset=utf-8;version=v2:
          type: !include ../schemas/cosmos/rpc/v2/model/DescribeResponse-schema.json
          example:
            name: cassandra
            version: 1.0.24-3.0.10
            packagingVersion: "3.0"
            releaseVersion: 24
            maintainer: support@mesosphere.io
            description: Apache Cassandra running on DC/OS
            tags:
              - data
              - database
              - nosql
